steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  env:
  - 'JOB_NAME=sample-$BUILD_ID'
  - 'NEW_VAR=$_NEW_VAR'
  args:
    - -c
    - |
          ./start.sh
- name: 'ubuntu'
  args: ['echo', 'hello ${_SUB_VALUE}']
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: bash
  env:
  - 'JOB_NAME=sample-$BUILD_ID'
  - 'NEW_VAR=$_NEW_VAR'
  - 'REPO_NAME=$REPO_NAME'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TAG_NAME=$TAG_NAME'
  - 'REVISION_ID=$REVISION_ID'
  - 'COMIT_SHA=$COMMIT_SHA'
  args:
    - -c
    - |
          ./upload-config.sh
substitutions:
    _SUB_VALUE: world
    _NEW_VAR: vaaaaaaarrrr