steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  env:
  - 'JOB_NAME=$_JOB_NAME'
  - 'NEW_VAR=sample-$BUILD_ID'
  args:
    - -c
    - |
          ./start.sh
- name: 'ubuntu'
  args: ['echo', 'hello ${_SUB_VALUE}']
substitutions:
    _SUB_VALUE: world
    _JOB_NAME: jobbbbbbbb